### ISSUE TITLE
Wrong Link of project

### ISSUE THREAD

**Issue by AshutoshSingh47** [AshutoshSingh47/Portfolio_Website#1]
There is a issue with the link in Project Cards 

Issue : Wrong link is included in Android Project Live Demo section.
Right link : https://appetize.io/app/vxjjun2p5zbku7wewbrtnuc2ee?device=pixel4&osVersion=11.0&scale=75

![issue_1_img](https://github.com/AshutoshSingh47/Portfolio_Website/assets/67503435/2b64dd86-ba01-42e1-9bdd-7d6c6c9fd40a)

**Comment by georgioupanayiotis** [comment]
@AshutoshSingh47 can you assign this to me ?
