### ISSUE TITLE
Navbar home item link highlight

### ISSUE THREAD

**Issue by AshutoshSingh47** [AshutoshSingh47/Portfolio_Website#2]
The home link in navbar menu must always be highlighted and if someone clicks on another item then the home link highlightning must get removed.

![issue_2_img_a](https://github.com/AshutoshSingh47/Portfolio_Website/assets/67503435/994e597a-5097-4d8b-a73e-4d85092f0f2a)
![issue_2_img_b](https://github.com/AshutoshSingh47/Portfolio_Website/assets/67503435/97b04d41-71a5-4340-8322-786dcd9bde5a)
![issue_2_img_c](https://github.com/AshutoshSingh47/Portfolio_Website/assets/67503435/3242cb60-a151-41b0-8222-6bc6e0db426e)

**Comment by georgioupanayiotis** [comment]
@AshutoshSingh47 can you assign this to me?

**Comment by AshutoshSingh47** [comment]
> @AshutoshSingh47 can you assign this to me?

Yes please.
